// src/topics.js
const Dynamic = [
  "Introduction to Dynamic Web Applications",
  "Introduction to Dynamic Web Applications",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "DOM and Event Fundamentals",
  "DOM and Event Fundamentals | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 1",
  "Introduction to JS & Variables",
  "A Note on Software Compatibility",
  "Primitive Types & Conditionals",
  "Primitive Types & Conditionals | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Input Element & Math Functions",
  "Input Element & Math Functions | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 2",
  "Arrays & Objects",
  "Arrays & More DOM Manipulations",
  "Arrays & More DOM Manipulations | Reading Material",
  "More Array Methods | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice I",
  "MCQ Practice II",
  "Coding Practice",
  "JS Coding Practice 1",
  "JS Coding Practice 2",
  "JS Coding Platform Walk-through",
  "Objects",
  "Objects | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice I",
  "MCQ Practice II",
  "Coding Practice",
  "JS Coding Practice 3",
  "JS Coding Practice 4",
  "JS Coding Practice 5",
  "JS Coding Practice 6",
  "JS Programming Coding Practice",
  "Daily Quiz - 3",
  "Fetch & Callbacks",
  "Callbacks & Schedulers",
  "Callbacks & Schedulers | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Event Listeners and More Events",
  "Event Listeners and More Events | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 4",
  "Fetch & Callbacks 2",
  "Hypertext Transfer Protocol (HTTP)",
  "Hypertext Transfer Protocol (HTTP) | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "HTTP Requests using JS",
  "HTTP Requests using JS | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 5",
  "Fetch & Callbacks 3",
  "Wikipedia Search Application",
  "Wikipedia Search Application | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 6",
  "Forms",
  "Forms",
  "Forms | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Forms | Part 2",
  "Forms | Part 2 | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 7",
];

export default Dynamic;
