const responsive = [
  "Responsive Web Design & Bootstrap Grid System",
  "Introduction to Responsive Web Design",
  "Introduction to Responsive Web Design | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Bootstrap Grid System",
  "Bootstrap Grid System | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 1",
  "Bootstrap Grid System and Navbar",
  "Bootstrap Grid System | Part 2",
  "Bootstrap Grid System | Part 2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Bootstrap Navbar",
  "Bootstrap Navbar | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 2",
  "CSS Selectors & Inheritance",
  "CSS Selectors & Inheritance",
  "CSS Selectors & Inheritance | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "More CSS Selectors",
  "More CSS Selectors | Reading Material",
  "CSS Selectors | Learning by Playing",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "Class Room Quiz C",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 3",
  "CSS Specificity & Cascade and Developing Layouts",
  "CSS Specificity & Cascade",
  "CSS Specificity & Cascade | Reading Material",
  "Classroom Quiz A",
  "Classroom Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Banner Section",
  "Banner Section | Reading Material",
  "Classroom Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 4",
  "Developing Layouts 2",
  "Why Choose Us? Section",
  "Why Choose Us? Section | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Explore Menu Section",
  "Explore Menu Section | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 5",
  "Developing Layouts 3",
  "Healthy Food, Delivery and Payment, Thanking Customers Sections",
  "Healthy Food, Delivery and Payment, Thanking Customers Sections | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Follow Us Section and More Styling",
  "Follow Us Section and More Styling | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 6",
  "CSS Gradients & Transistions",
  "CSS Gradients & More Bootstrap Components",
  "CSS Gradients & More Bootstrap Components | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Transitions",
  "CSS Transitions | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 7",
  "CSS Transforms and Animations",
  "CSS Transforms",
  "CSS Transforms | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Animations",
  "CSS Animations | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 8",
  "Revision",
  "Responsive Summary Cheatsheet",
  "Build Your Own Responsive Website Course Quiz",
];

export default responsive;
