const topics = [
  "Introduction to HTML",
  "Introduction to HTML | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 1",
  "Introduction to CSS",
  "Introduction to CSS | Part 1",
  "Introduction to CSS | Part-1 Cheat Sheet",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Introduction to CSS | Part 2",
  "Introduction to CSS | Part-2 Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 2",
  "Intro to CSS & CSS Box Model",
  "Introduction to CSS | Part 3",
  "Introduction to CSS | Part-3 Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Introduction to CSS Box Model | Part 1",
  "Introduction to CSS Box Model | Part 1 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 3",
  "CSS Box Model & Intro to Bootstrap",
  "Introduction to CSS Box Model | Part 2",
  "Introduction to CSS Box Model | Part 2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Introduction to Bootstrap",
  "Introduction to Bootstrap | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 4",
  "Introduction to Bootstrap & Developing Layouts",
  "Introduction to Bootstrap | Part 2",
  "Introduction to Bootstrap | Part 2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Favourite Places Section",
  "Favourite Places Section | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 5",
  "Developing Layouts",
  "Approach to Develop a Layout",
  "Approach to Develop a Layout | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "A Note on Bootstrap Versions",
  "Favourite Place Detailed View Section",
  "Favourite Place Detailed View Section | Reading Material",
  "Class Room Quiz",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 6",
  "Website Integration",
  "Website Integration | Reading Material",
  "Class Room Quiz",
  "MCQ Practice",
  "Coding Practice",
  "Website Integration | Part 2",
  "Website Integration | Part 2 | Reading Material",
  "Class Room Quiz",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 7",
  "HTML Hyperlinks",
  "Website: Behind the Scenes",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 8",
  "Introduction to HTML5 & HTML Semantic Elements",
  "Introduction to HTML5",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "Class Room Quiz C",
  "Coding Practice",
  "HTML Semantic Elements",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "Coding Practice",
  "Daily Quiz - 9",
  "Revision",
  "Static Summary Cheatsheet",
  "Build Your Own Static Website Course Quiz",
  "Responsive Web Design & Bootstrap Grid System",
  "Introduction to Responsive Web Design",
  "Introduction to Responsive Web Design | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Bootstrap Grid System",
  "Bootstrap Grid System | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 1",
  "Bootstrap Grid System and Navbar",
  "Bootstrap Grid System | Part 2",
  "Bootstrap Grid System | Part 2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Bootstrap Navbar",
  "Bootstrap Navbar | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 2",
  "CSS Selectors & Inheritance",
  "CSS Selectors & Inheritance | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "More CSS Selectors",
  "More CSS Selectors | Reading Material",
  "CSS Selectors | Learning by Playing",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "Class Room Quiz C",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 3",
  "CSS Specificity & Cascade",
  "CSS Specificity & Cascade | Reading Material",
  "Classroom Quiz A",
  "Classroom Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Banner Section",
  "Banner Section | Reading Material",
  "Classroom Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 4",
  "Developing Layouts 2",
  "Why Choose Us? Section",
  "Why Choose Us? Section | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Explore Menu Section",
  "Explore Menu Section | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 5",
  "Developing Layouts 3",
  "Healthy Food, Delivery and Payment, Thanking Customers Sections",
  "Healthy Food, Delivery and Payment, Thanking Customers Sections | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Follow Us Section and More Styling",
  "Follow Us Section and More Styling | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 6",
  "CSS Gradients & More Bootstrap Components",
  "CSS Gradients & More Bootstrap Components | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Transitions",
  "CSS Transitions | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 7",
  "CSS Transforms",
  "CSS Transforms | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Animations",
  "CSS Animations | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 8",
  "Revision",
  "Responsive Summary Cheatsheet",
  "Build Your Own Responsive Website Course Quiz",
  "Sizing Elements and Box Sizing",
  "Sizing Elements and Handling Overflow",
  "Sizing Elements and Handling Overflow | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Box Sizing",
  "Box Sizing | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Daily Quiz - 1",
  "Introduction to CSS Flexbox",
  "Introduction to CSS Flexbox | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice 1",
  "MCQ Practice 2",
  "Coding Practice",
  "Introduction to CSS Flexbox | Part 2",
  "Class Room Quiz A",
  "Introduction to CSS Flexbox | Part 2 | Reading Material",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 2",
  "Introduction to CSS Flexbox | Part 3",
  "Introduction to CSS Flexbox | Part 3 | Reading Material",
  "Flexbox Froggy Game",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice I",
  "MCQ Practice II",
  "Coding Practice",
  "CSS Media Queries",
  "CSS Media Queries | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice 1",
  "Coding Practice 2",
  "Daily Quiz - 3",
  "Flexbox Sizing",
  "Flexbox Sizing | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "On‑Demand Session",
  "On‑Demand Session | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice I",
  "MCQ Practice II",
  "Coding Practice",
  "Daily Quiz - 4",
  "CSS Grid | Part 1",
  "CSS Grid Part - 1 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Grid | Part 2",
  "CSS Grid Part - 2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 5",
  "CSS Grid | Part 3",
  "CSS Grid Part - 3 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Grid | Part 4",
  "CSS Grid Part - 4 | Reading Material",
  "CSS Grid | Learning by Playing",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 6",
  "CSS Positioning | Part 1",
  "CSS Positioning Part - 1 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "CSS Positioning | Part 2",
  "CSS Positioning Part -2 | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 7",
  "Introduction to Tailwind CSS",
  "Introduction to Tailwind CSS | Reading Material",
  "Class Room Quiz A",
  "Class Room Quiz B",
  "MCQ Practice",
  "Coding Practice",
  "Introduction to Tailwind CSS | Part 2",
  "Introduction to Tailwind CSS - Part 2 | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 8",
  "Building a Responsive Website with Tailwind CSS",
  "Building a Responsive Website with Tailwind CSS | Reading Material",
  "Class Room Quiz A",
  "MCQ Practice",
  "Coding Practice",
  "Daily Quiz - 9",
];

export default topics;
